"""
AuraLink Gemini Configuration Module

This module provides a dynamic interface to the Gemini AI API,
handling authentication and model discovery.
"""

import os
import google.generativeai as genai

def configure_gemini(api_key):
    """Configure the Gemini API with the provided key"""
    genai.configure(api_key=api_key)
    
def discover_models():
    """Discover available Gemini models"""
    try:
        models = genai.list_models()
        gemini_models = []
        
        for model in models:
            # Extract model name from path
            model_name = model.name.split('/')[-1]
            if 'gemini' in model_name.lower():
                gemini_models.append(model_name)
                
        return gemini_models
    except Exception as e:
        print(f"Error discovering models: {e}")
        return []

def get_best_model():
    """Get the best available Gemini model for summarization"""
    models = discover_models()
    
    # Preferred models in order (free tier)
    preferred = [
        "gemini-2.5-flash-lite",
        "gemini-2.5-flash", 
        "gemini-2.5-pro",
        "gemini-1.5-flash",
        "gemini-pro"
    ]
    
    # Return the first preferred model that's available
    for model in preferred:
        if model in models:
            return model
            
    # If none of our preferred models are available, return the first available one
    if models:
        return models[0]
        
    # If no models are available, return None
    return None

def summarize(text, max_length=80):
    """
    Summarize text using the best available Gemini model
    
    Args:
        text (str): Text to summarize
        max_length (int): Maximum length of the summary
        
    Returns:
        str: The summary
        bool: Whether the summary was generated by Gemini or a fallback
    """
    model_name = get_best_model()
    
    if not model_name:
        return None, False
        
    try:
        model = genai.GenerativeModel(model_name=model_name)
        prompt = f"Summarize this email concisely in {max_length} characters or less:\n\n{text}"
        response = model.generate_content(prompt)
        summary = response.text.strip()
        
        # Ensure the summary is within the maximum length
        if len(summary) > max_length:
            summary = summary[:max_length-3] + "..."
            
        return summary, True
    except Exception as e:
        print(f"Error summarizing with {model_name}: {e}")
        return None, False